- job:
    name: vitrage-dashboard-integration-tests
    parent: horizon-integration-tests
    required-projects:
      - name: openstack/horizon
      - name: openstack/vitrage
      - name: openstack/python-vitrageclient
      - name: openstack/vitrage-dashboard
    roles:
      - zuul: openstack-infra/devstack
      - zuul: openstack/horizon
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      devstack_plugins:
        vitrage: https://opendev.org/openstack/vitrage
        vitrage-dashboard: https://opendev.org/openstack/vitrage-dashboard
      devstack_services:
        horizon: true
      tox_envlist: integration

- project:
    templates:
      - horizon-nodejs10-jobs-nonvoting
      - horizon-non-primary-django-jobs
      - openstack-python3-victoria-jobs-horizon
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - vitrage-dashboard-integration-tests:
            voting: false

